### ISSUE TITLE
Could not find ros_system_fingerprint module

### ISSUE THREAD

**Issue by bijoua29** [MetroRobots/ros_system_fingerprint#13]
Tried to run 'ros2 run system_fingerprint imprint' and it crashes with the following trace:

Traceback (most recent call last):
  File "/opt/ros/rolling/lib/system_fingerprint/scripts/imprint", line 33, in <module>
    sys.exit(load_entry_point('UNKNOWN==0.5.0', 'console_scripts', 'imprint')())
  File "/opt/ros/rolling/lib/system_fingerprint/scripts/imprint", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/ros/rolling/lib/python3.10/site-packages/system_fingerprint/imprint.py", line 5, in <module>
    from ros_system_fingerprint import modules
ModuleNotFoundError: No module named 'ros_system_fingerprint'
[ros2run]: Process exited with failure 1

**Comment by DLu** [comment]
Apologies! This is indeed a problem in the binary version. It was fixed in https://github.com/MetroRobots/ros_system_fingerprint/pull/7 and the new version will be available with the next rolling sync.
